//go:build ignore

// genemoji regenerates static/emoji/{fr,en}.json, the data files behind the
// list modal's emoji picker (static/js/emoji-picker.js), from a pinned
// release of emojibase-data (MIT; its labels and keywords are the Unicode
// CLDR annotations). Run from the repository root:
//
//	go run tools/genemoji/main.go
//
// Then bump the service worker cache version in static/sw.js so installed
// PWAs pick the new files up.
//
// Output shape, one file per UI language:
//
//	{"source": "...", "groups": [{"id": "smileys", "e": [entry, ...]}, ...]}
//
// where each entry is [emoji, label, keywords, tone?, version?]:
//   - keywords: the CLDR keywords, lowercased, split into words, minus any
//     word already in the label — space-separated, search-only.
//   - tone: 0 = no skin-tone variants, 1 = insert the modifier after the
//     first code point (👍 → 👍🏽), 2 = after the first and last code points
//     (🧑‍🤝‍🧑 → 🧑🏽‍🤝‍🧑🏽). Any FE0F right after an insertion point is dropped.
//     Checked against emojibase's own variant list; anything else gets 0.
//   - version: the Emoji version, only written when >= 13 — older releases
//     render everywhere this PWA runs, newer ones are hidden client-side
//     when the device's font can't draw them.
//
// Trailing zero fields are omitted. This file is build-ignored: it is a
// maintenance tool, not part of the server binary.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const emojibaseVersion = "17.0.0"

// Emojibase group numbers → the picker's category ids (static/js/
// emoji-picker.js keys its icons and i18n labels on these). Group 2
// (skin-tone/hair components) and ungrouped entries (bare regional
// indicator letters) are deliberately left out.
var groups = []struct {
	num int
	id  string
}{
	{0, "smileys"},
	{1, "people"},
	{3, "nature"},
	{4, "food"},
	{5, "travel"},
	{6, "activities"},
	{7, "objects"},
	{8, "symbols"},
	{9, "flags"},
}

type emoji struct {
	Emoji   string   `json:"emoji"`
	Label   string   `json:"label"`
	Group   *int     `json:"group"`
	Order   int      `json:"order"`
	Tags    []string `json:"tags"`
	Version float64  `json:"version"`
	Skins   []struct {
		Emoji string `json:"emoji"`
		Tone  any    `json:"tone"`
	} `json:"skins"`
}

var skinTones = []string{"\U0001F3FB", "\U0001F3FC", "\U0001F3FD", "\U0001F3FE", "\U0001F3FF"}

func main() {
	for _, lang := range []string{"fr", "en"} {
		data, err := fetch(lang)
		if err != nil {
			log.Fatalf("%s: %v", lang, err)
		}
		out, err := build(data)
		if err != nil {
			log.Fatalf("%s: %v", lang, err)
		}
		path := filepath.Join("static", "emoji", lang+".json")
		if err := os.WriteFile(path, out, 0o644); err != nil {
			log.Fatal(err)
		}
		log.Printf("wrote %s (%d bytes)", path, len(out))
	}
}

func fetch(lang string) ([]emoji, error) {
	url := "https://cdn.jsdelivr.net/npm/emojibase-data@" + emojibaseVersion + "/" + lang + "/data.json"
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var data []emoji
	if err := json.Unmarshal(body, &data); err != nil {
		return nil, err
	}
	return data, nil
}

func build(data []emoji) ([]byte, error) {
	byGroup := map[int][]emoji{}
	for _, e := range data {
		if e.Group != nil {
			byGroup[*e.Group] = append(byGroup[*e.Group], e)
		}
	}

	var buf bytes.Buffer
	buf.WriteString(`{"source":"emojibase-data ` + emojibaseVersion +
		` (MIT, github.com/milesj/emojibase), labels and keywords from Unicode CLDR (Unicode License v3). Generated by tools/genemoji.","groups":[`)
	for gi, g := range groups {
		list := byGroup[g.num]
		if len(list) == 0 {
			return nil, fmt.Errorf("group %d (%s) is empty", g.num, g.id)
		}
		sort.Slice(list, func(i, j int) bool { return list[i].Order < list[j].Order })
		if gi > 0 {
			buf.WriteString(",")
		}
		fmt.Fprintf(&buf, "\n{\"id\":%q,\"e\":[", g.id)
		for i, e := range list {
			entry := []any{e.Emoji, e.Label, keywords(e.Label, e.Tags)}
			tone := toneRule(e)
			version := 0.0
			if e.Version >= 13 {
				version = e.Version
			}
			switch {
			case version > 0:
				entry = append(entry, tone, version)
			case tone > 0:
				entry = append(entry, tone)
			}
			if entry[2] == "" && len(entry) == 3 {
				entry = entry[:2]
			}
			line, err := json.Marshal(entry)
			if err != nil {
				return nil, err
			}
			if i > 0 {
				buf.WriteString(",")
			}
			buf.WriteString("\n")
			buf.Write(line)
		}
		buf.WriteString("\n]}")
	}
	buf.WriteString("\n]}\n")
	return buf.Bytes(), nil
}

// keywords flattens the CLDR keyword phrases into unique lowercase words
// that the label doesn't already contain — the picker searches the label
// and this string together, so repeating a label word would only cost bytes.
func keywords(label string, tags []string) string {
	seen := map[string]bool{}
	for _, w := range strings.Fields(strings.ToLower(label)) {
		seen[w] = true
	}
	var words []string
	for _, tag := range tags {
		for _, w := range strings.Fields(strings.ToLower(tag)) {
			if !seen[w] {
				seen[w] = true
				words = append(words, w)
			}
		}
	}
	return strings.Join(words, " ")
}

// toneRule reports which insertion rule (see the file comment) reproduces
// every one of e's single-tone variants, or 0 if it has none or neither
// rule matches (e.g. a couple whose two people can carry different tones —
// those stay reachable by pasting them into the free-text field).
func toneRule(e emoji) int {
	var single []string
	for _, s := range e.Skins {
		if n, ok := s.Tone.(float64); ok {
			single = append(single, skinTones[int(n)-1]+"\x00"+s.Emoji)
		}
	}
	if len(single) != len(skinTones) {
		return 0
	}
	for _, rule := range []int{1, 2} {
		ok := true
		for _, pair := range single {
			tone, want, _ := strings.Cut(pair, "\x00")
			if applyTone(e.Emoji, tone, rule) != want {
				ok = false
				break
			}
		}
		if ok {
			return rule
		}
	}
	log.Printf("no tone rule matches %s (%s); leaving it untoned", e.Emoji, e.Label)
	return 0
}

// applyTone mirrors applyTone in static/js/emoji-picker.js.
func applyTone(base, tone string, rule int) string {
	runes := []rune(base)
	insertAt := map[int]bool{0: true}
	if rule == 2 {
		insertAt[len(runes)-1] = true
	}
	var b strings.Builder
	for i := 0; i < len(runes); i++ {
		b.WriteRune(runes[i])
		if insertAt[i] {
			b.WriteString(tone)
			if i+1 < len(runes) && runes[i+1] == '️' {
				i++
			}
		}
	}
	return b.String()
}
