package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"trakka/internal/backup"
	"trakka/internal/db"
	"trakka/internal/models"
)

func newBackupTestApplication(t *testing.T) *Application {
	t.Helper()
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	dbPath := filepath.Join(t.TempDir(), "trakka.db")
	d, err := db.Open(dbPath, logger)
	if err != nil {
		t.Fatalf("opening test db: %v", err)
	}
	t.Cleanup(func() { _ = d.Close() })
	return &Application{
		DB:      d,
		Logger:  logger,
		Backups: backup.New(backup.Options{DB: d, DBPath: dbPath, Logger: logger, Location: time.UTC}),
	}
}

// TestAdminBackupsEndpointsRequireAdmin calls every backup handler as a
// non-admin and expects a 403 from each — a backup is a copy of every
// account's data, and a restore replaces it.
func TestAdminBackupsEndpointsRequireAdmin(t *testing.T) {
	app := newBackupTestApplication(t)
	member := &models.User{ID: 42, IsAdmin: false}

	routes := []struct {
		method, path, body string
		handler            http.HandlerFunc
	}{
		{http.MethodGet, "/api/v1/admin/backups", "", app.handleAdminBackupsStatus},
		{http.MethodPut, "/api/v1/admin/backups/config", `{}`, app.handleAdminBackupsConfigUpdate},
		{http.MethodPost, "/api/v1/admin/backups/test", `{}`, app.handleAdminBackupsTest},
		{http.MethodPost, "/api/v1/admin/backups/run", "", app.handleAdminBackupsRun},
		{http.MethodGet, "/api/v1/admin/backups/remote", "", app.handleAdminBackupsRemoteList},
		{http.MethodPost, "/api/v1/admin/backups/key/export", "", app.handleAdminBackupsKeyExport},
		{http.MethodPost, "/api/v1/admin/backups/restore", "", app.handleAdminBackupsRestore},
	}
	for _, rt := range routes {
		req := withUser(httptest.NewRequest(rt.method, rt.path, strings.NewReader(rt.body)), member)
		rec := httptest.NewRecorder()
		rt.handler(rec, req)
		if rec.Code != http.StatusForbidden {
			t.Errorf("%s %s as a non-admin: got %d, want 403", rt.method, rt.path, rec.Code)
		}
	}

	// The key must not have been generated by a rejected export.
	if _, ok, err := app.Backups.CurrentKey(); ok || err != nil {
		t.Fatalf("a non-admin export created a key (ok=%v, err=%v)", ok, err)
	}
}

func TestAdminBackupsConfigAndKeyExport(t *testing.T) {
	app := newBackupTestApplication(t)
	admin := &models.User{ID: 1, IsAdmin: true}

	// Invalid configuration is a 400 with the reason.
	req := withUser(httptest.NewRequest(http.MethodPut, "/api/v1/admin/backups/config",
		strings.NewReader(`{"webdav_url":"javascript:alert(1)","frequency":"daily","time":"03:00","retention":7}`)), admin)
	rec := httptest.NewRecorder()
	app.handleAdminBackupsConfigUpdate(rec, req)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("invalid URL: got %d: %s", rec.Code, rec.Body.String())
	}

	req = withUser(httptest.NewRequest(http.MethodPut, "/api/v1/admin/backups/config", strings.NewReader(
		`{"webdav_url":"https://cloud.example.com/remote.php/dav/files/me/backups","webdav_username":"me","webdav_password":"s3cret",
		  "auto_enabled":true,"frequency":"weekly","time":"04:30","weekday":1,"retention":5}`)), admin)
	rec = httptest.NewRecorder()
	app.handleAdminBackupsConfigUpdate(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("valid config: got %d: %s", rec.Code, rec.Body.String())
	}
	if strings.Contains(rec.Body.String(), "s3cret") {
		t.Fatal("the WebDAV password was echoed back")
	}
	var st backup.Status
	if err := json.Unmarshal(rec.Body.Bytes(), &st); err != nil {
		t.Fatal(err)
	}
	if !st.Config.WebDAVPasswordSet || st.Config.Frequency != "weekly" || st.Config.Weekday != 1 || !st.Key.Exists || st.Key.Saved {
		t.Fatalf("status after save = %+v", st)
	}
	if len(st.Alerts) != 1 || st.Alerts[0].Code != backup.AlertKeyNotSaved {
		t.Fatalf("expected the key_not_saved alert, got %+v", st.Alerts)
	}

	req = withUser(httptest.NewRequest(http.MethodPost, "/api/v1/admin/backups/key/export", nil), admin)
	rec = httptest.NewRecorder()
	app.handleAdminBackupsKeyExport(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("key export: got %d: %s", rec.Code, rec.Body.String())
	}
	var exported backup.ExportedKey
	if err := json.Unmarshal(rec.Body.Bytes(), &exported); err != nil {
		t.Fatal(err)
	}
	if k, err := backup.ParseKey(exported.FileContent); err != nil || k.Fingerprint() != st.Key.Fingerprint {
		t.Fatalf("exported key file doesn't parse back to the instance key (err=%v)", err)
	}
	if got, _ := app.Backups.Status(context.Background()); !got.Key.Saved || len(got.Alerts) != 0 {
		t.Fatalf("after export: key=%+v alerts=%+v", got.Key, got.Alerts)
	}
}

// buildRestoreRequest assembles the multipart body the admin console sends.
func buildRestoreRequest(t *testing.T, fields map[string]string, file []byte) *http.Request {
	t.Helper()
	var body bytes.Buffer
	mw := multipart.NewWriter(&body)
	if file != nil {
		fw, err := mw.CreateFormFile("file", "trakka-backup.tkb")
		if err != nil {
			t.Fatal(err)
		}
		_, _ = fw.Write(file)
	}
	for k, v := range fields {
		if err := mw.WriteField(k, v); err != nil {
			t.Fatal(err)
		}
	}
	if err := mw.Close(); err != nil {
		t.Fatal(err)
	}
	req := httptest.NewRequest(http.MethodPost, "/api/v1/admin/backups/restore", &body)
	req.Header.Set("Content-Type", mw.FormDataContentType())
	return req
}

// TestAdminBackupsRestoreUpload restores an uploaded backup through the
// handler — with the file part arriving before the key, which the handler
// must accept — and checks the refusal codes for a wrong key and garbage.
func TestAdminBackupsRestoreUpload(t *testing.T) {
	ctx := context.Background()
	app := newBackupTestApplication(t)
	admin := &models.User{ID: 1, IsAdmin: true}
	hash := "x"
	if _, err := app.DB.CreateUser(ctx, "kept@example.com", &hash, nil, nil, "kept"); err != nil {
		t.Fatal(err)
	}

	exported, err := app.Backups.ExportKey(ctx)
	if err != nil {
		t.Fatal(err)
	}
	key, err := backup.ParseKey(exported.Key)
	if err != nil {
		t.Fatal(err)
	}
	snap := filepath.Join(t.TempDir(), "snap.db")
	if err := app.DB.SnapshotTo(ctx, snap); err != nil {
		t.Fatal(err)
	}
	plain, err := os.ReadFile(snap)
	if err != nil {
		t.Fatal(err)
	}
	var encrypted bytes.Buffer
	if err := backup.Encrypt(&encrypted, bytes.NewReader(plain), key); err != nil {
		t.Fatal(err)
	}

	if _, err := app.DB.CreateUser(ctx, "dropped@example.com", &hash, nil, nil, "dropped"); err != nil {
		t.Fatal(err)
	}

	other, _ := backup.GenerateKey()
	// Change the key's last character to a different one, whatever it is.
	typo := exported.Key[:len(exported.Key)-1] + "Q"
	if strings.HasSuffix(exported.Key, "Q") {
		typo = exported.Key[:len(exported.Key)-1] + "R"
	}
	for name, tc := range map[string]struct {
		fields map[string]string
		file   []byte
		code   string
	}{
		"wrong key":    {map[string]string{"key": other.String()}, encrypted.Bytes(), "wrong_key"},
		"garbage file": {map[string]string{"key": exported.Key}, []byte("hello"), "not_a_backup"},
		"typo in key":  {map[string]string{"key": typo}, encrypted.Bytes(), "invalid_key"},
	} {
		rec := httptest.NewRecorder()
		app.handleAdminBackupsRestore(rec, withUser(buildRestoreRequest(t, tc.fields, tc.file), admin))
		var resp map[string]string
		_ = json.Unmarshal(rec.Body.Bytes(), &resp)
		if rec.Code != http.StatusBadRequest || resp["code"] != tc.code {
			t.Errorf("%s: got %d %v, want 400 code %s", name, rec.Code, resp, tc.code)
		}
	}
	if _, err := app.DB.GetUserByEmail(ctx, "dropped@example.com"); err != nil {
		t.Fatal("a rejected restore changed the live database")
	}

	// The real thing, pasting the whole .key file content as the key.
	rec := httptest.NewRecorder()
	app.handleAdminBackupsRestore(rec, withUser(buildRestoreRequest(t, map[string]string{"key": exported.FileContent}, encrypted.Bytes()), admin))
	if rec.Code != http.StatusOK {
		t.Fatalf("restore: got %d: %s", rec.Code, rec.Body.String())
	}
	if _, err := app.DB.GetUserByEmail(ctx, "kept@example.com"); err != nil {
		t.Fatalf("pre-backup user missing after restore: %v", err)
	}
	if _, err := app.DB.GetUserByEmail(ctx, "dropped@example.com"); !errors.Is(err, db.ErrNotFound) {
		t.Fatalf("post-backup user should be gone after restore, got %v", err)
	}

	// Neither a file nor a remote name: rejected before anything happens.
	rec = httptest.NewRecorder()
	app.handleAdminBackupsRestore(rec, withUser(buildRestoreRequest(t, map[string]string{"key": exported.Key}, nil), admin))
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("no backup given: got %d", rec.Code)
	}
}

// TestAdminBackupsRunNotConfigured: "Sauvegarder maintenant" before any
// WebDAV URL is saved is a clear 400, not a background failure.
func TestAdminBackupsRunNotConfigured(t *testing.T) {
	app := newBackupTestApplication(t)
	rec := httptest.NewRecorder()
	app.handleAdminBackupsRun(rec, withUser(httptest.NewRequest(http.MethodPost, "/api/v1/admin/backups/run", nil), &models.User{ID: 1, IsAdmin: true}))
	if rec.Code != http.StatusBadRequest || !strings.Contains(rec.Body.String(), "not_configured") {
		t.Fatalf("got %d: %s", rec.Code, rec.Body.String())
	}
}
